叩き台作成
protomo-friends/Acoboo pull request #4
Opened 2024-02-26 13:45 UTC by shinamon610

close #3 

叩き台作ってみました。

2024-03-09 17:36 UTC, iorar requested changes

2024-03-09 18:10 UTC, iorar commented on docs/環境構築ガイド.md
ただのコメント：
環境構築ガイドはバックエンドとフロントエンドがとりあえず動く状態にならないと書けないので、現段階ではこの状態で良さそうですね～

2024-03-09 18:20 UTC, iorar requested changes

2024-03-09 18:20 UTC, iorar commented on docs/フロントアーキテクチャ.md
バックエンド側のドキュメントはこのPRには含まれていないことを考えると、このドキュメントはこのPRの所掌ではない気がしてます
フロントエンド・バックエンドそれぞれで最初にコミットするタイミングで作るのはどうでしょう？

2024-03-09 18:20 UTC, iorar commented on .github/PULL_REQUEST_TEMPLATE.md
もうちょい豪華でいいかもしれないです

- issue番号
- 実装内容の要約
- 特にレビューしてほしいところ
- チェックリスト
くらい？
↓これくらいの重さだと良さそうな気がします
https://qiita.com/Hymt/items/5153800009b339423214

2024-03-09 18:20 UTC, iorar commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] テストをパスしていますか？
[ ] カンバンで重複の有無やタスクの移動を確認しましたか？　もあると嬉しい気がします

2024-03-24 09:21 UTC, shinamon610 commented
@iorar 
wikiにドキュメントは書くってことになったので、プルリクテンプレート以外はそっちに書きます。
今の所、ドキュメントにフロントに限った内容が書かれているわけではないので、一旦wikiは分けないで書きます。

2024-03-24 09:43 UTC, shinamon610 commented
@iorar 
PRテンプレート更新しました!
再Reviewお願いします〜。

2024-06-19 12:17 UTC, iorar commented
lgtm

2024-06-19 12:18 UTC, iorar approved these changes

2024-09-16 12:38 UTC, merged